#ifndef MAX_STREAMS
  #define MAX_STREAMS 20
#endif

#ifndef CODEC_TYPE_VIDEO
  #define CODEC_TYPE_VIDEO AVMEDIA_TYPE_VIDEO
#endif

#ifndef CODEC_TYPE_AUDIO
  #define CODEC_TYPE_AUDIO AVMEDIA_TYPE_AUDIO
#endif

#ifndef PKT_FLAG_KEY
  #define PKT_FLAG_KEY AV_PKT_FLAG_KEY
#endif
